### PR TITLE
Changed with_firebird to 1

### PR DESCRIPTION
**Pull request by futureweb**
See: https://github.com/iusrepo/php73/issues/4

### CODE REVIEW

**Comment by evitalis** [comment]
@futureweb Thank for for this PR. I did a quick test and it does not work as expected.

You don't need to add the extra global to the top of the file, this adds a bunch of excess changes. You just need to change the `global with_firebird` (line 56) in the else clause to a 1 and the expected subpackage is built.

The date in your changelog entry is also invalid.

Can you please make those couple tweaks and squash commits? I can help get you docs on this if needed.

Once those tweaks are in place this should be good to go.

**Comment by futureweb** [comment]
@evitalis - thx for pointing out the failures - which should have been obvious firsthand for me :-/
I guess / hope it's correct now ... ? ;-)

**Comment by evitalis** [comment]
No worries, it's a learning process and technically (other than the invalid date) just some not picking. But keeps things tidy. 

That being said from my test it built fine and the appropriate package was created.

@carlwgeorge for final review, though commits still need squashed. I am on mobile at the moment so trying to get a doc for this is awkward.

**Comment by carlwgeorge** [comment]
Thanks @futureweb for starting this PR, and thanks @evitalis for the review.  CI is now passing and the overall change looks good to me.  I'll squash the commits while merging.

**Pull request merged**
