### PR TITLE
Enable WebP support when using bundled GD

### PR DESCRIPTION
**Pull request by futureweb**
Enable WebP support when using bundled GD

### CODE REVIEW

**Comment by carlwgeorge** [comment]
This looks good to me.  I've got CI setup up now so packages have already been built.  You can download them from here (unsigned) to test.

https://cirrus-ci.com/task/6334934881402880

**Comment by futureweb** [comment]
missed incrementing Release Nr. - made new PR with incremented Release Nr.: https://github.com/iusrepo/php73/pull/10
Not that Familiar with Github yet - is there a better way of doing such changes afterwards than creating a new PR? Like editing the existing PR? Or how to get those 2 PR together? Maybe you got a little Hint for me on this? ;-)

**Comment by futureweb** [comment]
alright - got it into this PR ... guess you can Stash it when merging into master? As I didn't see an easy way to stash online in Github?!

**Comment by futureweb** [comment]
btw) tested the new RPM - WebP is working as expected! ;-)

**Comment by carlwgeorge** [comment]
Ah I totally missed the release not being bumped when I said it looked good.  Glad you caught that yourself.

As you realized, you can change your pull request just by pushing more commits to the pull request branch.  I can squash the commits when I merge them.

Thanks for testing those directly from the CI.  I'll merge and publish this.

**Pull request merged**
